# Generated by Django 3.0.7 on 2020-10-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='status',
            field=models.CharField(default='queued', max_length=100),
        ),
    ]
